apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
  namespace: default
  labels:
    app: admin-app
spec:
  selector:
    matchLabels:
      app: admin-app
  replicas: 1
  revisionHistoryLimit: 10
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - image: scg130/vue-admin
          imagePullPolicy: IfNotPresent
          name: admin-app
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            timeoutSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: admin-app-svc
  namespace: default
  labels:
    app: admin-app
spec:
  type: NodePort
  ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30003
  selector:
    app: admin-app